- id: autometate
  name: autoMETAte
  description: This hook populates a human and machine readable metadata file automatically.
  entry: python src/auto_meta/cli.py
  language: python
  types: [python]
